load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "all_metrics",
    deps = [
        "//src/grading/metrics/example:planning_limit_checker",
        "//src/grading/metrics/example:speed_checker",
    ],
    visibility = ["//visibility:public"],
)
